version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
  # vue-ui:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   container_name: vue-ui
  #   volumes:
  #      - ./my-app:/usr/src/app/my-app
  #      - /usr/src/app/my-app/node_modules