version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/ubuntu:latest
    steps:
      - checkout
      - run:
          name: Login to DockerHub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - run:
          name: Install Python
          command: |
            apt-get update && apt-get install -y
            python3.8
            python3-pip
      - run:
          name: Install Packages
          command: |
            apt install python3-dev libproj-dev proj-data proj-bin libgeos-dev -y
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            python -m py_compile manage.py
workflows:
  build_test:
    jobs:
      - run_tests
