version: 2.1
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Install Packages
          command: |
            sudo apt install libproj-dev proj-data proj-bin libgeos-dev -y
      - run:
          name: Install Python Dependencies
          command: |
            echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
            pip install --user -r requirements.txt
      - run:
          name: Run Unit Tests
          command: |
            python -m py_compile manage.py
            echo 'Compiled without any errors.'
workflows:
  build_test:
    jobs:
      - run_tests
